console.log(__filename);
var arr = [1, 2, 3, 4, 5];
console.log("原数组" + arr);
var deleteElems = arr.splice(1, 2, 110, 111);
console.log("删除的元素" + deleteElems.toString());
console.log("splice后的数组" + arr);
console.log("-----------------");
var arr1 = [1, 2, 3, 4, 5];
console.log("原数组" + arr1);
var sliceelems = arr1.slice(1, 2);
console.log("截取的数组元素" + sliceelems);
console.log("slice后的数组" + arr1);
var sliceelems1 = arr1.slice(1);
console.log("截取的数组元素有" + sliceelems1);
console.log("-----------------");
var arr2 = [1, 3, 2, 6, 4, 9, 8, 4, 5];
arr2.forEach(function (e) {
    console.log(e);
});
var filterarr1 = arr2.filter(function (e) { return e > 5; });
console.log(filterarr1);
var maparr1 = arr2.map(function (e) { return e * 2; });
console.log(maparr1);
arr2.reduce(function (pre, cur) {
    console.log("嘿嘿");
    console.log(pre);
    console.log(cur);
    console.log("嘿嘿");
    return pre + cur;
});
var someFlag = arr2.some(function (e) { return e > 8; });
console.log(someFlag);
var someFlag1 = arr2.some(function (e) { return e > 9; });
console.log(someFlag1);
var everyFlag = arr2.every(function (e) { return e > 5; });
console.log(everyFlag);
var everyFlag1 = arr2.every(function (e) { return e < 10; });
console.log(everyFlag1);
console.log(arr2.length);
var newSize = arr2.push(888);
console.log(arr2);
var deleleElem = arr2.pop();
console.log(arr2);
var newSize1 = arr2.unshift(123);
console.log(arr2);
var shiftElem = arr2.shift();
console.log(arr2);
var concatResult = arr2.concat(123123, 123124);
console.log(concatResult);
console.log(arr2);
var index = arr2.indexOf(3);
console.log(index);
var notFound = arr2.indexOf(1231);
console.log(notFound);
var reverseArr = arr2.reverse();
console.log(reverseArr);
console.log(arr2.join(""));
console.log(arr2.join("--"));
console.log(arr2.join("."));
var sortArr = arr2.sort();
console.log(sortArr);
var sortArr1 = arr2.sort(function (a, b) {
    return a - b;
});
console.log(sortArr1);
var sortArr2 = arr2.sort(function (a, b) {
    return b - a;
});
console.log(sortArr2);
console.log(arr2);
//# sourceMappingURL=TestArray.clas.js.map